### ISSUE TITLE
Erase Flash on upload.

### ISSUE THREAD

**Issue by Duyvest** [ayushsharma82/ElegantOTA#113]
With ArduinoIDE there is an option to erase flash on upload.  This can sometimes fix errors and crashes and is good to for a fresh start if a lot of changes have been made.  

Is this possible to do this with ElegantOTA? 

Thanks

**Comment by Daryavahus** [comment]
I think it's not possible because of OTA library, right now. It's  stored in flash. When We would move library to IRAM, we would format flash and copy  uploaded file. I see that firmware uploaded directly from IDE via USB has less unexpexted error and reboots.
Or let the Arduino IDE  creates bin file with max available size - 1024KB(free space is empty).

**Comment by ayushsharma82** [comment]
It is not possible when doing an OTA update. The process is completely different to how 'flash' procedure is handled by ArduinoIDE.
